/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoricoIdRouteImport } from './routes/historico.$id'
import { Route as HistoricoIdRelatorioRouteImport } from './routes/historico.$id.relatorio'

const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoIdRoute = HistoricoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HistoricoRoute,
} as any)
const HistoricoIdRelatorioRoute = HistoricoIdRelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => HistoricoIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/historico': typeof HistoricoRouteWithChildren
  '/historico/$id': typeof HistoricoIdRouteWithChildren
  '/historico/$id/relatorio': typeof HistoricoIdRelatorioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/historico': typeof HistoricoRouteWithChildren
  '/historico/$id': typeof HistoricoIdRouteWithChildren
  '/historico/$id/relatorio': typeof HistoricoIdRelatorioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/historico': typeof HistoricoRouteWithChildren
  '/historico/$id': typeof HistoricoIdRouteWithChildren
  '/historico/$id/relatorio': typeof HistoricoIdRelatorioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/historico'
    | '/historico/$id'
    | '/historico/$id/relatorio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/historico'
    | '/historico/$id'
    | '/historico/$id/relatorio'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/historico'
    | '/historico/$id'
    | '/historico/$id/relatorio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  HistoricoRoute: typeof HistoricoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico/$id': {
      id: '/historico/$id'
      path: '/$id'
      fullPath: '/historico/$id'
      preLoaderRoute: typeof HistoricoIdRouteImport
      parentRoute: typeof HistoricoRoute
    }
    '/historico/$id/relatorio': {
      id: '/historico/$id/relatorio'
      path: '/relatorio'
      fullPath: '/historico/$id/relatorio'
      preLoaderRoute: typeof HistoricoIdRelatorioRouteImport
      parentRoute: typeof HistoricoIdRoute
    }
  }
}

interface HistoricoIdRouteChildren {
  HistoricoIdRelatorioRoute: typeof HistoricoIdRelatorioRoute
}

const HistoricoIdRouteChildren: HistoricoIdRouteChildren = {
  HistoricoIdRelatorioRoute: HistoricoIdRelatorioRoute,
}

const HistoricoIdRouteWithChildren = HistoricoIdRoute._addFileChildren(
  HistoricoIdRouteChildren,
)

interface HistoricoRouteChildren {
  HistoricoIdRoute: typeof HistoricoIdRouteWithChildren
}

const HistoricoRouteChildren: HistoricoRouteChildren = {
  HistoricoIdRoute: HistoricoIdRouteWithChildren,
}

const HistoricoRouteWithChildren = HistoricoRoute._addFileChildren(
  HistoricoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  HistoricoRoute: HistoricoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
